apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: frontend
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: node-app-frontend
        image: "{{ .Values.image.frontend.repo }}:{{ .Values.image.frontend.tag }}"
        imagePullPolicy: Always
        env:
          - name: BACKEND_URL
            valueFrom:
              configMapKeyRef:
                name: node-app-configmap
                key: BACKEND_URL
        resources:
          requests:
            memory: "128Mi"
            cpu: "200m"
          limits:
            memory: "256Mi"
            cpu: "250m"       
